name: Manage Repo Settings

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name'
        required: true
        default: 'public-ghas'

jobs:
  update-settings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run repo management script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx tsx ./scripts/github/repo-management.ts ${{ github.event.inputs.repository }}
